{% set version = "1.5.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-workflowr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/workflowr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/workflowr/workflowr_{{ version }}.tar.gz
  sha256: f4a1534852d3f3650bd3d7575eead8a9b7b7548602e3986bcf0479fba6a96d4b

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-callr
    - r-fs >=1.2.4
    - r-getpass
    - r-git2r
    - r-glue
    - r-httr
    - r-knitr >=1.18
    - r-rmarkdown >=1.7
    - r-rprojroot
    - r-rstudioapi >=0.5
    - r-stringr >=1.1.0
    - r-whisker
    - r-yaml
  run:
    - r-base
    - r-callr
    - r-fs >=1.2.4
    - r-getpass
    - r-git2r
    - r-glue
    - r-httr
    - r-knitr >=1.18
    - r-rmarkdown >=1.7
    - r-rprojroot
    - r-rstudioapi >=0.5
    - r-stringr >=1.1.0
    - r-whisker
    - r-yaml

test:
  commands:
    - $R -e "library('workflowr')"           # [not win]
    - "\"%R%\" -e \"library('workflowr')\""  # [win]

about:
  home: https://github.com/jdblischak/workflowr
  license: MIT
  license_file: LICENSE
  summary: Provides a workflow for your analysis projects by combining literate programming ('knitr'
    and 'rmarkdown') and version control ('Git', via 'git2r') to generate a website
    containing time-stamped, versioned, and documented results.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: workflowr
# Type: Package
# Title: A Framework for Reproducible and Collaborative Data Science
# Date: 2019-06-07
# Version: 1.4.0
# Authors@R: c( person("John", "Blischak", role = c("aut", "cre"), email = "jdblischak@uchicago.edu", comment = c(ORCID = "0000-0003-2634-9879")), person("Peter", "Carbonetto", role = c("aut"), comment = c(ORCID = "0000-0003-1144-6780")), person("Matthew", "Stephens", role = c("aut"), comment = c(ORCID = "0000-0001-5397-9257")), person("Luke", "Zappia", role = c("ctb"), comment = "Instructions for hosting with GitLab"), person("Pierre", "Formont", role = c("ctb"), comment = "Support for hosting with Shiny Server"), person("Tim", "Trice", role = c("ctb"), comment = "Instructions for sharing common code"), person("Jiaxiang", "Li", role = c("ctb"), comment = "Function wflow_toc() to create table of contents"))
# Description: Provides a workflow for your analysis projects by combining literate programming ('knitr' and 'rmarkdown') and version control ('Git', via 'git2r') to generate a website containing time-stamped, versioned, and documented results.
# URL: https://github.com/jdblischak/workflowr
# BugReports: https://github.com/jdblischak/workflowr/issues
# Depends: R (>= 3.2.5)
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# Imports: callr, fs (>= 1.2.4), getPass, git2r, glue, httr, knitr (>= 1.18), methods, rmarkdown (>= 1.7), rprojroot, rstudioapi (>= 0.5), stringr (>= 1.1.0), tools, utils, whisker, yaml
# RoxygenNote: 6.1.1
# Suggests: clipr, covr, devtools, miniUI (>= 0.1.1), shiny (>= 0.13), spelling, testthat, withr
# VignetteBuilder: knitr
# SystemRequirements: pandoc (>= 1.12.3) - http://pandoc.org
# Language: en-US
# NeedsCompilation: no
# Packaged: 2019-06-08 13:40:10 UTC; jdb-work
# Author: John Blischak [aut, cre] (<https://orcid.org/0000-0003-2634-9879>), Peter Carbonetto [aut] (<https://orcid.org/0000-0003-1144-6780>), Matthew Stephens [aut] (<https://orcid.org/0000-0001-5397-9257>), Luke Zappia [ctb] (Instructions for hosting with GitLab), Pierre Formont [ctb] (Support for hosting with Shiny Server), Tim Trice [ctb] (Instructions for sharing common code), Jiaxiang Li [ctb] (Function wflow_toc() to create table of contents)
# Maintainer: John Blischak <jdblischak@uchicago.edu>
# Repository: CRAN
# Date/Publication: 2019-06-08 14:10:03 UTC
