{% set version = '1.1.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-workflowr
  version: {{ version|replace("-", "_") }}

source:
  fn: workflowr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/workflowr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/workflowr/workflowr_{{ version }}.tar.gz
  sha256: 020f8111e09ef0129ddac3d7e57079ac750fffc5ead50e9c2c6b9a556abc7762

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-r.utils
    - r-callr
    - r-getpass
    - r-git2r
    - r-glue
    - r-knitr >=1.18
    - r-rmarkdown >=1.7
    - r-rprojroot
    - r-rstudioapi
    - r-stringr >=1.1.0
    - r-whisker
    - r-yaml

  run:
    - r-base
    - r-r.utils
    - r-callr
    - r-getpass
    - r-git2r
    - r-glue
    - r-knitr >=1.18
    - r-rmarkdown >=1.7
    - r-rprojroot
    - r-rstudioapi
    - r-stringr >=1.1.0
    - r-whisker
    - r-yaml

test:
  commands:
    - $R -e "library('workflowr')"           # [not win]
    - "\"%R%\" -e \"library('workflowr')\""  # [win]

about:
  home: https://github.com/jdblischak/workflowr
  license: MIT
  summary: Combines literate programming ('knitr' and 'rmarkdown') and version control ('Git',
    via 'git2r') to generate a website containing time-stamped, versioned, and documented
    results.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
