appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ob9GvMCAUEjqEh9OrJQEx+t60IS2DUtsrQelyrORCxo5a0a94AM+FCtKIEej294Ms6THjBVHJESxgyzrfcYbjt8IaOEuzQKQNg0V9TKgmZzhZ0zFji2oe9abDgKrqWsiAoEljo6A701WWHIaXDMrYGBRF/yqcjuDtnLUQTUEPSfN0Rku1IwzyuqqTESVzBCU7rx/p9UEZXF2S7UgdtqtGylLTvce7JfQHL0LZHxYoJgAPhAeS1Gnc7/w3syETAXdAdvGMbsWGoBa/ifMrNi2JCzE65d5hdwMEsPfdNFMcoZ8RiHbl2WuqKqDo9xspjgNfshYUabnG4GZnZ0lagLMR1gLe/jnbQNvUzACWKRuBnU8vbeJddo3d344An1SumAKoMtIHgSqGtudqlN6DIRRbwQWQfKcwAXVSTe4ndMp29r19ZamuCtRoRGwF9OOOrwneeO5gdY5L2OlOB7ItDI7wOQftA/5ulKOQOwS5WwMm80kC9Zm7rXCqW0Nc4HYRxRlA53Qcg2YwNex9B9k/RbOQtFvDW7xU3mP7od1N3MavRID5JPtOtbG7PklEE6z4oqgg6oPakSjl5pjok4Df8lXp8bABXKA/a7rH+5Cny3Duaq64U7SgO6C3wKs3FB4/dq3CRysQzUeJC8k7MYcX35OzUFE/PLXCpSHt2cqNF3tP6o=}
