travis:
  secure:
    BINSTAR_TOKEN: Gj9Dy+hZ5dcUDejWO++AM6lZjEu/HgzKjTuj1ynHS5ug07K+qvzb4RjuQgbVVpwQ3TIhTQCbKpxwWmxXjqLN0BZx+FzJ9zP+yLnOzh2Y2TI/5a3xIvrIZCUc27vwOKKmhMywT2wVuylf+CoITofQLBZ8sIKEg8N3Pxnc4vnPFZg86xP7bI30HSi5b+vf9Or7vchqboA+Cr2ZGi3eoXPRE+BaXGAMPJdLGkw0ZHvmB8IIyYaqj699Bjt2/Gvxwv67kS81MAUf12/6WkgHo4gYL+P81wbGd3ZxB4xlVZhl4HD11l+HLGjWvturghUNQC6HMJH9DsAA7idnJI1HJuk7gIkTyGzOVTmFkFmQjcvFTNFbyBCyJEpCOp1zzmShJk6lfnJU+1UoHH/mq9vC8vFW3ApBQBsE25S4+C72ImeWe9v0q0ZDLAfP1RMByZ1x7jZhaTwnuh3/27hcumngnFPvIaX1Ld3tbhAmCJbLv5rxvLqoruepmTeR2T4uMa4cpTpPU/pk4TorJXMDQZWDQK+oqhMqV42YkB1m20P8VylC1PEULEFWkuzgg+4Gbd3J+lIeT3xZi/hdEwv08sULP2Ij7kL4kPf9GfMD8NTwzzAoWQnBdvyDfraVSDAbSKaKQR5inQckIUx/Z7k6VRVVHblfwAc6cKAv/6fCKsKJiC9ghq4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
